version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    volumes:
      - /tmp/kafka:/kafka
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.1.113
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1

      # KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      # KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "mytopic2:2:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
